version: "3.1"
services:
    www:
        build: .
        command: >
            sh -c "find /var/www/html -type d -exec chmod 775 {} \; &&
                   find /var/www/html -type f -exec chmod 644 {} \;"
        ports: 
            - "8641:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - my-main-net
    db:
        image: mysql:8.0
        ports: 
            - "3308:3308"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dockerExample
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - my-main-net
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8692:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
            - my-main-net
volumes:
    mysql_data:
    
networks:
    my-main-net:
      external: true 